# Generated by Django 5.0.1 on 2024-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_Email',
            new_name='user_email',
        ),
    ]
